name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.14.0 # 必要なNode.jsのバージョンを指定

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - name: Setup database
        run: pnpm --filter=backend backend:setup

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: pnpm cy:ci
        # run: pnpm cy:ci
